# Historic
SAVEHIST=10000
HISTSIZE=10000
HISTFILE=~/.zsh_history


# Zplug
source /usr/share/zsh/scripts/zplug/init.zsh

zplug "zsh-users/zsh-history-substring-search"
zplug "zsh-users/zsh-autosuggestions"
zplug "plugins/git",   from:oh-my-zsh
zplug "plugins/docker",   from:oh-my-zsh
zplug "zsh-users/zsh-completions"

if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi
zplug load
#
# Config asdf
. /opt/asdf-vm/asdf.sh
eval "$(starship init zsh)"
eval "$(zoxide init zsh)"


# Aliases
alias vi=nvim
alias ls=eza
alias ll=eza -l
alias la=eza -la
alias tree=eza --tree

export EDITOR=nvim
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
